import { DEFAULT_COLOR } from "../../config/config";

const initialState = {
  nombre: null,
  estado: "borrador",
  description: null,
  hcolor: DEFAULT_COLOR,
  terminosCondiciones: null,
  bodyEmail: "",
  creationDate: new Date().toLocaleString(),
  fields: [
    {
      field_required: true,
      field_type: "email",
      field_label: "Mail",
      field_name: "Mail",
      field_id: "Mail",
      field_value: "",
      field_placeholder: "Ingrese su correo",
      field_min: "0",
      field_max: "999",
      field_order: "1",
    },
    {
      field_required: true,
      field_type: "number",
      field_label: "Teléfono",
      field_name: "Teléfono",
      field_id: "Teléfono",
      field_value: "",
      field_placeholder: "Ingrese su teléfono",
      field_min: "0",
      field_max: "16",
      field_order: "2",
    },
    {
      field_required: true,
      field_type: "number",
      field_label: "DNI",
      field_name: "DNI",
      field_id: "DNI",
      field_value: "",
      field_placeholder: "Ingrese su Documento",
      field_min: "8",
      field_max: "8",
      field_order: "3",
    },
  ],
  banner: null,
};
export default initialState;
