export { default as getParams } from "./getParams";
export { default as postData } from "./postData";
export { default as getForm } from "./getForm";
export { default as className } from "./className";
export { default as replaceUrl } from "./replaceUrl";
export { default as createFormData } from "./createFormData";
export { default as getAllForms } from "./getAllForms";
export { emailIsValid } from "./regex";
export { default as postForm } from "./postForm";
export { default as asteriscos } from "./asteriscos";
export { default as getOrderId } from "./getOrderId";
