const formulario = {
    nombre: null,
    estado: "borrador",
    dni: null,
    email: null,
    description: null,
    hcolor: '#266AAD',
    terminosCondiciones: null,
    bodyEmail: "",
    creationDate: new Date().toLocaleString(),
    fields: [
        //se agrega Nombre y Apellido como obligatorios
        {
            field_required: true,
            field_type: "text",
            field_label: "Nombre",
            field_name: "Nombre",
            field_id: "Nombre",
            field_value: "",
            field_placeholder: "Ingrese su Nombre",
            field_min: "2",
            field_max: "50",
            field_order: "1",
        },
        {
            field_required: true,
            field_type: "text",
            field_label: "Apellido",
            field_name: "Apellido",
            field_id: "Apellido",
            field_value: "",
            field_placeholder: "Ingrese su Apellido",
            field_min: "2",
            field_max: "50",
            field_order: "2",
        },
        {
            field_required: true,
            field_type: "email",
            field_label: "Mail",
            field_name: "Mail",
            field_id: "Mail",
            field_value: "",
            field_placeholder: "Ingrese su correo",
            field_min: "0",
            field_max: "999",
            field_order: "3",
        },
        {
            field_required: true,
            field_type: "number",
            field_label: "Teléfono",
            field_name: "Teléfono",
            field_id: "Teléfono",
            field_value: "",
            field_placeholder: "Ingrese su teléfono",
            field_min: "0",
            field_max: "16",
            field_order: "4",
        },
        {
            field_required: true,
            field_type: "number",
            field_label: "DNI",
            field_name: "DNI",
            field_id: "DNI",
            field_value: "",
            field_placeholder: "Ingrese su Documento",
            field_min: "0",
            field_max: "8",
            field_minValue: "0",
            //field_maxValue: "99999999",
            field_order: "5",
        },
    ],
    banner: null,
}


export const crearState = {
    formulario: { ...formulario },
    keyTab: "detalle",
    loadingSubmit: false,
    preview: false,
    fileSizeAllowed: true,
    uuidForm: null,
    labelAcepto: "",
}